"use strict";
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.getApiNotesId = exports.getApiNotes = exports.postApiNotes = void 0;
/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * Second Brain API
 * OpenAPI spec version: 1.0.0
 */
var axios = require("axios");
/**
* @summary Create a note
*/
var postApiNotes = function (noteInput, options) {
    return axios.default.post("/api/notes", noteInput, options);
};
exports.postApiNotes = postApiNotes;
/**
 * @summary List notes
 */
var getApiNotes = function (params, options) {
    return axios.default.get("/api/notes", __assign(__assign({}, options), { params: __assign(__assign({}, params), options === null || options === void 0 ? void 0 : options.params) }));
};
exports.getApiNotes = getApiNotes;
/**
 * @summary Get a note
 */
var getApiNotesId = function (id, options) {
    return axios.default.get("/api/notes/".concat(id), options);
};
exports.getApiNotesId = getApiNotesId;
