/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * Second Brain API
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export type GetApiNotesParams = {
tag?: string;
};

export interface Note {
  createdAt?: string;
  id?: number;
  path?: string;
  tags?: string[];
  title?: string;
  updatedAt?: string;
}

export interface NoteInput {
  content: string;
  tags: string[];
  title: string;
}





  /**
 * @summary Create a note
 */
export const postApiNotes = <TData = AxiosResponse<Note>>(
    noteInput: NoteInput, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/notes`,
      noteInput,options
    );
  }

/**
 * @summary List notes
 */
export const getApiNotes = <TData = AxiosResponse<Note[]>>(
    params?: GetApiNotesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/notes`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Get a note
 */
export const getApiNotesId = <TData = AxiosResponse<Note>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/notes/${id}`,options
    );
  }

export type PostApiNotesResult = AxiosResponse<Note>
export type GetApiNotesResult = AxiosResponse<Note[]>
export type GetApiNotesIdResult = AxiosResponse<Note>
