"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.db = void 0;
var express_1 = require("express");
var notes_1 = require("./routes/notes");
var node_postgres_1 = require("drizzle-orm/node-postgres");
var pg_1 = require("pg");
var cors_1 = require("cors");
var pool = new pg_1.Pool({ connectionString: process.env.DATABASE_URL });
exports.db = (0, node_postgres_1.drizzle)(pool);
var app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
app.use('/api/notes', notes_1.default);
exports.default = app;
